### PR TITLE
feat: add binary for linux ia32

### PR DESCRIPTION
**Pull request by RaisinTen**
Based on the changes upto:
https://github.com/llvm/llvm-project/commit/632668c1c0e7dcf97154d2e377491cdc8cb6963c

Build script:

```console
git clone https://github.com/llvm/llvm-project.git
cd llvm-project
git reset --hard 632668c1c0e7dcf97154d2e377491cdc8cb6963c
mkdir build
cd build
cmake -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DLLVM_BUILD_STATIC=true -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_GENERATOR_PLATFORM=x86 ../llvm
ninja clang-format
strip bin/clang-format
```

### CODE REVIEW

**Comment by mprobst** [comment]
Sorry for the long wait, I was on a prolonged leave.

Can you share what command / configuration you used to build these? I think I'll need to repro that myself; I cannot accept arbitrary binaries into the project that I didn't build, for security reasons (I hope you can understand that).

**Comment by RaisinTen** [comment]
@mprobst Sorry, I was busy working on my other PRs, so I couldn't really get back to you. I noticed that the way I built the binary earlier was not the right way as it was 94 MB! So, I have rebuilt it using the info given in the readme with some slight modifications as the default script did not work. I have updated the PR info with the script I used. I'll shoot a PR to update the same in the readme.

**Comment by RaisinTen** [comment]
PR to fix the build script: https://github.com/angular/clang-format/pull/71

**Comment by RaisinTen** [comment]
@mprobst gentle reminder, in case you forgot about reviewing this PR and the one I linked to above :)

**Comment by RaisinTen** [comment]
@mprobst bump

**Comment by mprobst** [comment]
Sorry, the bottleneck is that I do now know how to produce an i386 binary on an x64 machine (i.e. cross compile in llvm), and as I said above, I cannot just accept a compiled binary from a third party, for security reasons (not that I have reasons not to trust you, but general policy is to only accept changes that can be reviewed, and the binary dump here cannot be reviewed).

Do you have a suggestion for a cross compilation setup here?

**Comment by RaisinTen** [comment]
@mprobst I have updated the script in the PR description to build a 32-bit binary by adding the `-DCMAKE_GENERATOR_PLATFORM=x86` option to `cmake`. You could try this locally and then compare the file hashes. I can't test this myself because I don't use a 32-bit Linux anymore.

**Comment by mprobst** [comment]
If you don't use 32bit linux, nor do I - do we believe this really
helps anyone at this point?

**Comment by RaisinTen** [comment]
Eh, probably not. I'm okay with closing this at this point in time! :)

**Pull request closed without merging**
